# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOS_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Demo

  pod 'SnapKit', '~> 4.0.0'


  target 'iOS_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
